# Generated by Django 4.0.6 on 2022-07-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_delated',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='is_delated',
            new_name='is_deleted',
        ),
    ]
